add config to repo

diff --git a/.github/workflows/cmake.yml b/.github/workflows/cmake.yml
--- a/.github/workflows/cmake.yml
+++ b/.github/workflows/cmake.yml
@@ -113,27 +113,36 @@ jobs:
         
     - name: System - Setup configuration variable needed by super-projects
       run: |
-        if [[ $(git config -l | grep -q GITHUB.ACTIONS.PREBUILD.EXTERNAL.REPO; echo $?) != "0" ]]
+        if [[ ! -e GITHUB_ACTIONS_PREBUILD_CONFIG ]]
             then
-                git config GITHUB.ACTIONS.PREBUILD.EXTERNAL.REPO ${{env.GITHUB_ACTIONS_PREBUILD_EXTERNAL_REPO_FOLDER}}
-                echo "'git config GITHUB.ACTIONS.PREBUILD.EXTERNAL.REPO' has been updated"
+                git config -f GITHUB_ACTIONS_PREBUILD_CONFIG GITHUB.ACTIONS.PREBUILD.EXTERNAL.REPO ${{env.GITHUB_ACTIONS_PREBUILD_EXTERNAL_REPO_FOLDER}}
+                git add GITHUB_ACTIONS_PREBUILD_CONFIG
+                echo "'git config -f GITHUB_ACTIONS_PREBUILD_CONFIG GITHUB.ACTIONS.PREBUILD.EXTERNAL.REPO' has been updated"
             else
-                if [[ $(git config --get GITHUB.ACTIONS.PREBUILD.EXTERNAL.REPO) != ${{env.GITHUB_ACTIONS_PREBUILD_EXTERNAL_REPO_FOLDER}} ]]
+                if [[ $(git config -f GITHUB_ACTIONS_PREBUILD_CONFIG -l | grep -q GITHUB.ACTIONS.PREBUILD.EXTERNAL.REPO; echo $?) != "0" ]]
                     then
-                        echo
-                        echo "WARNING: values of 'config get GITHUB.ACTIONS.PREBUILD.EXTERNAL.REPO' and 'env.GITHUB_ACTIONS_PREBUILD_EXTERNAL_REPO_FOLDER' differ"
-                        echo
-                        if [[ -e ${{env.GITHUB_ACTIONS_PREBUILD_EXTERNAL_REPO_FOLDER}} ]]
+                        git config -f GITHUB_ACTIONS_PREBUILD_CONFIG GITHUB.ACTIONS.PREBUILD.EXTERNAL.REPO ${{env.GITHUB_ACTIONS_PREBUILD_EXTERNAL_REPO_FOLDER}}
+                        git add GITHUB_ACTIONS_PREBUILD_CONFIG
+                        echo "'git config -f GITHUB_ACTIONS_PREBUILD_CONFIG GITHUB.ACTIONS.PREBUILD.EXTERNAL.REPO' has been updated"
+                    else
+                        if [[ $(git config -f GITHUB_ACTIONS_PREBUILD_CONFIG --get GITHUB.ACTIONS.PREBUILD.EXTERNAL.REPO) != ${{env.GITHUB_ACTIONS_PREBUILD_EXTERNAL_REPO_FOLDER}} ]]
                             then
                                 echo
-                                echo "ERROR: env.GITHUB_ACTIONS_PREBUILD_EXTERNAL_REPO_FOLDER must not exist"
-                                echo "please move '${{env.GITHUB_ACTIONS_PREBUILD_EXTERNAL_REPO_FOLDER}}' to another location, or remove it"
+                                echo "WARNING: values of 'config get GITHUB.ACTIONS.PREBUILD.EXTERNAL.REPO' and 'env.GITHUB_ACTIONS_PREBUILD_EXTERNAL_REPO_FOLDER' differ"
                                 echo
-                                false
+                                if [[ -e ${{env.GITHUB_ACTIONS_PREBUILD_EXTERNAL_REPO_FOLDER}} ]]
+                                    then
+                                        echo
+                                        echo "ERROR: env.GITHUB_ACTIONS_PREBUILD_EXTERNAL_REPO_FOLDER must not exist"
+                                        echo "please move '${{env.GITHUB_ACTIONS_PREBUILD_EXTERNAL_REPO_FOLDER}}' to another location, or remove it"
+                                        echo
+                                        false
+                                fi
+                                mv -v $(git config -f GITHUB_ACTIONS_PREBUILD_CONFIG --get GITHUB.ACTIONS.PREBUILD.EXTERNAL.REPO) ${{env.GITHUB_ACTIONS_PREBUILD_EXTERNAL_REPO_FOLDER}}
+                                git config -f GITHUB_ACTIONS_PREBUILD_CONFIG GITHUB.ACTIONS.PREBUILD.EXTERNAL.REPO ${{env.GITHUB_ACTIONS_PREBUILD_EXTERNAL_REPO_FOLDER}}
+                                git add GITHUB_ACTIONS_PREBUILD_CONFIG
+                                echo "'git config -f GITHUB_ACTIONS_PREBUILD_CONFIG GITHUB.ACTIONS.PREBUILD.EXTERNAL.REPO' has been updated"
                         fi
-                        mv -v $(git config --get GITHUB.ACTIONS.PREBUILD.EXTERNAL.REPO) ${{env.GITHUB_ACTIONS_PREBUILD_EXTERNAL_REPO_FOLDER}}
-                        git config GITHUB.ACTIONS.PREBUILD.EXTERNAL.REPO ${{env.GITHUB_ACTIONS_PREBUILD_EXTERNAL_REPO_FOLDER}}
-                        echo "'git config GITHUB.ACTIONS.PREBUILD.EXTERNAL.REPO' has been updated"
                 fi
         fi
         true
@@ -157,7 +166,7 @@ jobs:
 
         git submodule foreach --recursive "\
                 git submodule init; \
-                git config -l | grep -q GITHUB_ACTIONS_PREBUILD.EXTERNAL_REPO && git submodule deinit \$(git config --get GITHUB_ACTIONS_PREBUILD.EXTERNAL_REPO); \
+                git config -f GITHUB_ACTIONS_PREBUILD_CONFIG -l | grep -q GITHUB_ACTIONS_PREBUILD.EXTERNAL_REPO && git submodule deinit \$(git config --get GITHUB_ACTIONS_PREBUILD.EXTERNAL_REPO); \
                 git submodule update; \
         "
 
