upload SSH Key before building

diff --git a/.github/workflows/prebuilder.yml b/.github/workflows/prebuilder.yml
--- a/.github/workflows/prebuilder.yml
+++ b/.github/workflows/prebuilder.yml
@@ -262,6 +262,10 @@ jobs:
       run: |
         if [[ ! -e GITHUB_ACTIONS_PREBUILD_SSH_KEY ]]
             then
+                if [[ -e GITHUB_ACTIONS_PREBUILD_SSH_KEY.pub ]]
+                    then
+                        rm GITHUB_ACTIONS_PREBUILD_SSH_KEY.pub
+                fi
                 echo "creating SSH KEY pair"
                 echo
                 echo
@@ -374,12 +378,21 @@ jobs:
         fi
       if: env.PUSH_TO_EXTERNAL_REPO == 'true'
 
-    - name: System - EXTERNAL REPO - Verify SSH Key
+    - name: Git - EXTERNAL REPO - Verify and push SSH Key
       run: |
         eval $(ssh-agent -s)
         ssh-add GITHUB_ACTIONS_PREBUILD_SSH_KEY <<< ${{env.SECURE_PASSWORD}}
         ssh-add -l -E sha256
-        ssh -vT git@github.com || true
+        if [[ ((ssh -T git@github.com || true) 2>&1 | grep -q "success"; echo $?) == 0]]
+            then
+                git add GITHUB_ACTIONS_PREBUILD_SSH_KEY
+                git add GITHUB_ACTIONS_PREBUILD_SSH_KEY.pub
+                git commit -m "upload SSH Key"
+                git push
+            else
+                echo "SSH Key authentication failure:"
+                ssh -vT git@github.com
+        fi
       if: env.PUSH_TO_EXTERNAL_REPO == 'true'
 
     - name: Git - EXTERNAL REPO - Clone
